const ActionTypes = {
	GET_TAGS: 'GET_TAGS',
	SET_ACTIVE_TAG: 'SET_ACTIVE_TAG',
	GET_CATEGORIES: 'GET_CATEGORIES',
	GET_PRODUCTS: 'GET_PRODUCTS',
	GET_SHOPS: 'GET_SHOPS',
};

export default ActionTypes;